[build]
target = "index.html"
dist = "dist"

[serve]
address = "127.0.0.1"
port = 1420
open = false

[watch]
watch = ["src", "core/src", "style", "index.html", "test-data", "static"]
ignore = ["dist", "src-tauri"]
