[package]
name = "rail-graph-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "rail-graph-server"
path = "main.rs"

[dependencies]
actix-web = "4"
actix-files = "0.6"
env_logger = "0.11"
serde = { version = "1.0", features = ["derive"] }
